# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "NWSplit58"
product_name = "NWSplit58"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "Nikolaj W. Steenberg"
chip = "rp2040"

[behavior.morse]
enable_flow_tap = false 
hold_on_other_press = true 
hold_timeout = "200ms"
gap_timeout = "200ms"

morses = [
  { tap = "esc",  hold = "lctl" }
]

[layout]
rows = 5
cols = 13
layers = 2
keymap = [
    [
        ["esc", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "-", "="],
        ["tjab", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "[", "]"],
        ["TD(0)", "A", "S", "D", "F", "G", "H", "J", "K", "L", ";", "'", "nuhs"],
        ["lsft", "Z", "X", "C", "V", "B", "N", "M", ",", ".", "/", "rsft", "rwin"],
        ["_", "_", "_", "lopt", "spc", "MO(1)", "ent", "bspc", "ropt", "_", "_", "_", "_"]
    ],
    [
        ["_", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11", "F12"],
        ["_", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "-", "="],
        ["_", "_", "_", "_", "_", "_", "left", "down", "up", "right", "_", "_", "_"],
        ["_", "nubs", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "del", "_", "_", "_", "_", "_"],
    ],
    [
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ],
    [
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ]
]

# Reset stored config every time you start keyboard
[storage]
clear_storage = false 

[split]
connection = "serial"

[split.central]
rows = 5
cols = 6
row_offset = 0
col_offset = 0
serial = [{ instance = "PIO0", tx_pin = "PIN_0", rx_pin = "PIN_1" }]

[split.central.matrix]
input_pins = ["PIN_20", "PIN_19", "PIN_18", "PIN_17", "PIN_16"]
output_pins = ["PIN_11", "PIN_10", "PIN_9", "PIN_8", "PIN_7", "PIN_6"]

[[split.peripheral]]
rows = 5
cols = 7
row_offset = 0
col_offset = 6
serial = [{ instance = "PIO0", tx_pin = "PIN_1", rx_pin = "PIN_0" }]

[split.peripheral.matrix]
input_pins = ["PIN_20", "PIN_19", "PIN_18", "PIN_17", "PIN_16"]
output_pins = ["PIN_6", "PIN_7", "PIN_8", "PIN_9", "PIN_10", "PIN_11", "PIN_12"]
