# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "NWSplit58"
product_name = "NWSplit58"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "nws"
chip = "rp2040"
usb_enable = true

[security]
unlock_keys = [[0, 1], [0, 2]]

[layout]
rows = 5
cols = 13
layers = 2
keymap = [
    [
        ["grv", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "-", "="],
        ["tab", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "[", "]"],
        ["TH(esc, lctrl)", "A", "S", "D", "F", "G", "H", "J", "K", "L", "_", "'", "nuhs"],
        ["lsft", "nubs", "Z", "X", "C", "V", "B", "N", "M", ",", ".", "/", "rwin"],
        ["_", "_", "_", "lopt", "spc", "MO(1)", "ent", "bspc", "ropt", "_", "_", "_", "_"],
    ],
    [
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ],
]

[storage]

[split]
connection = "serial"

[split.central]
rows = 5
cols = 6
row_offset = 0
col_offset = 0
serial = [
    { instance = "UART0", tx_pin = "PIN_0", rx_pin = "PIN_1" },
]
[split.central.matrix]
matrix_type = "normal"
input_pins = ["PIN_20", "PIN_19", "PIN_18", "PIN_17", "PIN_16"]
output_pins = ["PIN_11", "PIN_10", "PIN_9", "PIN_8", "PIN_7", "PIN_6"]

[split.peripheral]
rows = 5
cols = 7
row_offset = 0
col_offset = 6
serial = [
    { instance = "UART0", tx_pin = "PIN_0", rx_pin = "PIN_1" },
]
[split.peripheral.matrix]
matrix_type = "normal"
input_pins = ["PIN_20", "PIN_19", "PIN_18", "PIN_17", "PIN_16"]
output_pins = ["PIN_6", "PIN_7", "PIN_8", "PIN_9", "PIN_10", "PIN_11", "PIN_12"]
output_pins_inverted = true