name: Build RMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - "**"

env:
  RUST_BACKTRACE: 1

jobs:
  build:
    uses: haobogu/rmk/.github/workflows/user_build.yml@main
    with:
      keyboard_toml_path: "keyboard.toml"
      vial_json_path: "vial.json"
